apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-game-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 2048-game
  template: 
    metadata:
      labels:
        app: 2048-game
    spec:
      containers:
      - name: 2048-container
        image: thipparthiavinash/mycalapp-awar05:latest
        ports:
        - containerPort: 80
